"""Generate apps/modified_puls_web/js/presets.js with embedded teaching presets.

Reads the Silver Creek CSVs from apps/modified_puls_web/data/ and emits an ES module with all
presets as plain data (so the app works offline with no fetch).

Run from the repo root:  python scripts/build_presets.py
"""

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "apps" / "modified_puls_web" / "data"
OUT = ROOT / "apps" / "modified_puls_web" / "js" / "presets.js"


def preset(pid, label, blurb, time, inflow, storage, discharge):
    return {
        "id": pid,
        "label": label,
        "blurb": blurb,
        "hydro": {"timeMin": list(map(float, time)), "inflowCfs": list(map(float, inflow))},
        "curve": {"storageAcft": list(map(float, storage)), "dischargeCfs": list(map(float, discharge))},
    }


# Shared flood used by the two contrasting basin presets (isolates the storage curve's effect).
BASIN_TIME = list(range(0, 250, 10))
BASIN_INFLOW = [
    0,
    15,
    45,
    95,
    170,
    260,
    340,
    395,
    420,
    400,
    355,
    300,
    245,
    195,
    150,
    113,
    83,
    60,
    43,
    30,
    20,
    13,
    8,
    5,
    3,
]

presets = []

# 1. Built-in sample (matches the Dash app's sample data).
presets.append(
    preset(
        "sample",
        "Sample event (gentle)",
        "A small, smooth event with a well-matched pond. Good first look at routing.",
        [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
        [5, 10, 20, 35, 55, 70, 60, 40, 25, 12, 6],
        [0.0, 1.5, 4.0, 8.0, 13.0, 19.0, 26.0],
        [0.0, 3.0, 8.0, 16.0, 28.0, 45.0, 68.0],
    )
)

# 2. Small pond — little attenuation (small storage relative to flood volume).
presets.append(
    preset(
        "small-pond",
        "Small pond — little attenuation",
        "Same flood, a small pond. Storage is tiny next to the flood volume, so the peak barely drops.",
        BASIN_TIME,
        BASIN_INFLOW,
        [0.0, 0.6, 1.5, 2.8, 4.5, 6.8, 9.5],
        [0.0, 60.0, 140.0, 240.0, 360.0, 500.0, 660.0],
    )
)

# 3. Large flat basin — strong attenuation (large storage at the same discharges).
presets.append(
    preset(
        "large-basin",
        "Large flat basin — strong attenuation",
        "Same flood, a large flat basin. Lots of storage holds water back, cutting and delaying the peak.",
        BASIN_TIME,
        BASIN_INFLOW,
        [0.0, 9.0, 24.0, 48.0, 82.0, 128.0, 185.0],
        [0.0, 60.0, 140.0, 240.0, 360.0, 500.0, 660.0],
    )
)

# 4. Silver Creek 100-yr — real instructor data.
sc_hydro = pd.read_csv(DATA / "inflow_Silver_Ck_J020_blw_EX_100YR_2020.csv")
sc_curve = pd.read_csv(DATA / "SVSQ_Silver_Ck_R020_EX.csv")
presets.append(
    preset(
        "silver-creek-100yr",
        "Silver Creek 100-yr (real data)",
        "A real 100-yr inflow and reservoir rating. The storage is small next to this flood, so attenuation is modest.",
        sc_hydro.iloc[:, 0].tolist(),
        sc_hydro.iloc[:, 1].tolist(),
        sc_curve.iloc[:, 0].tolist(),
        sc_curve.iloc[:, 1].tolist(),
    )
)

header = (
    "// AUTO-GENERATED by scripts/build_presets.py — do not edit by hand.\n"
    "// Built-in teaching examples, embedded so the app works offline.\n\n"
)
body = "export const PRESETS = " + json.dumps(presets, indent=2) + ";\n\n"
body += 'export const DEFAULT_PRESET_ID = "sample";\n'

OUT.write_text(header + body, encoding="utf-8")
print(f"wrote {OUT} with {len(presets)} presets")
